### ISSUE TITLE
Optimization with numpy operations

### ISSUE THREAD

**Issue by clementcaron** [CapucineBoudin/GameOfLife_CapucineBoudin_CDOF2#1]
The count_neighbors function is called for each cell in the grid, making it one of the most frequently executed parts of the code. If you want to optimize it here's a advice:
**Use Numpy Operations:** Since the grid is a Numpy array, you can leverage Numpy's efficient computation capabilities. Instead of manually iterating over each neighbor, you can use slicing and Numpy's vectorized operations to count neighbors. This would eliminate the nested for-loop and reduce the function's complexity.

The update_grid function updates each cell in the grid based on the number of neighbors. And here's an advice:
**Parallel Processing:** The current implementation updates the grid cell by cell in a sequential manner. If the hardware and environment allow, implementing parallel processing can significantly speed up this process. Each cell's state in the next generation is independent of others (based on the current generation), making this a good candidate for parallel computation.

**Comment by CapucineBoudin** [comment]
Regarding the count_neighbors function, you're absolutely right that using Numpy operations can greatly improve its efficiency. By leveraging Numpy's slicing and vectorized operations, we can avoid the manual iteration over each neighbor. This will not only eliminate the nested for-loop but also reduce the complexity of the function. I have updated the code accordingly to incorporate these optimizations.

As for the update_grid function, you suggested implementing parallel processing to speed up the cell updates. I completely agree with this idea. Since each cell's state in the next generation is independent of others, parallel processing can be a suitable approach to take advantage of parallel computation capabilities. However, the implementation of parallel processing depends on the hardware and environment in which the code is executed. Therefore, I have left the implementation as it is in the current code, but it can be further optimized by incorporating parallel processing if the hardware and environment allow.
